---

- name: install environnement de dev formation simplon
  hosts: simplon
  remote_user: dylan

  tasks:
    - name: installation editeur de texte
      apt: name-{{ item }} update_cache-yes state-latest
      with_items:
        - vim
        - visual-studio-code


...